### Create restaurant (owner must be authenticated)
POST http://localhost:8080/api/restaurants
Content-Type: application/json

{
  "ownerId": "Michael",
  "name": "Trattoria Roma",
  "address": {
    "street": "Via Milano",
    "number": "12",
    "postalCode": "20100",
    "city": "Milan",
    "country": "Italy"
  },
  "emailAddress": "contact@trattoriaroma.it",
  "pictures": [
    "https://example.com/images/front.jpg",
    "https://example.com/images/menu.jpg"
  ],
  "cuisineType": "ITALIAN",
  "minPrepTime": 15,
  "maxPrepTime": 25,
  "openingTime": "12:00",
  "closingTime": "23:00",
  "openDays": [
    "MONDAY",
    "FRIDAY",
    "SATURDAY",
    "SUNDAY"
  ]
}

###

GET http://localhost:8080/customer/restaurants

###

POST http://localhost:8080/api/foodmenus/dishes
Content-Type: application/json

{
  "restaurantId": "2f2416a6-3149-4441-a96d-5ead2d3162b3",
  "name": "Pizza",
  "description": "yummy cheese and tomato sauce",
  "price": 14.99,
  "pictureUrl": "noPic",
  "tags": "italian,cheese,fast-food",
  "dishType": "MAIN"
}

###

PATCH http://localhost:8080/api/foodmenus/2f2416a6-3149-4441-a96d-5ead2d3162b3/dishes/a94345ca-49d0-4867-be11-fdef4e0d0cb7/publish

###

PATCH http://localhost:8080/api/foodmenus/2f2416a6-3149-4441-a96d-5ead2d3162b3/dishes/a94345ca-49d0-4867-be11-fdef4e0d0cb7
Content-Type: application/json

{
  "name": "Sushi",
  "description": "CHANGED",
  "price": 1000,
  "pictureUrl": "CHANGED",
  "tags": "CHANGED",
  "dishType": "DESSERT"
}
###

PATCH http://localhost:8080/api/foodmenus/2f2416a6-3149-4441-a96d-5ead2d3162b3/dishes/a94345ca-49d0-4867-be11-fdef4e0d0cb7/unpublish

###

PATCH http://localhost:8080/api/foodmenus/2f2416a6-3149-4441-a96d-5ead2d3162b3/dishes/61f7c6b0-ef03-43e3-9e46-b8c8dc15fc04/out-of-stock

###

PATCH http://localhost:8080/api/foodmenus/2f2416a6-3149-4441-a96d-5ead2d3162b3/dishes/61f7c6b0-ef03-43e3-9e46-b8c8dc15fc04/available

###

POST http://localhost:8080/api/foodmenus/dishes
Content-Type: application/json

{
  "restaurantId": "2f2416a6-3149-4441-a96d-5ead2d3162b3",
  "name": "Scrambled Eggs",
  "description": "delicious egg scramble",
  "price": 3.99,
  "pictureUrl": "noPic",
  "tags": "breakfast,cheese,fast-food",
  "dishType": "STARTER"
}

###

PATCH http://localhost:8080/api/foodmenus/2f2416a6-3149-4441-a96d-5ead2d3162b3/dishes/b15263ac-267c-449f-8ab9-7867a960c088
Content-Type: application/json

{
  "name": "2ND CHANGE",
  "description": "SECOND",
  "price": 1000,
  "pictureUrl": "SECOND",
  "tags": "SECOND",
  "dishType": "DESSERT"
}
###

###

POST http://localhost:8080/api/foodmenus/27a66c5f-2c7e-4e89-a453-14b07b7a4af9/dishes/apply-pending

###

PATCH http://localhost:8080/api/foodmenus/dishes/schedule
Content-Type: application/json

{
  "restaurantId": "2f2416a6-3149-4441-a96d-5ead2d3162b3",
  "dishIds": [
    "a94345ca-49d0-4867-be11-fdef4e0d0cb7",
    "ca16d725-970f-4385-a6a4-575e9a360688"
  ],
  "publicationTime": "2025-10-14T21:24:00",
  "stateToBecome": "PUBLISHED"
}