GET http://localhost:8080/api/customers/restaurants

###

GET http://localhost:8080/api/customers/restaurants/b52bd8cb-4f06-49df-948b-a5424ba0e964/dishes

###

POST http://localhost:8080/api/orders
Content-Type: application/json

{
  "restaurantId": "375686e5-2edb-40b2-805e-15da931ca25d",
  "lines": [
    {
      "dishId": "92da893a-6513-4904-b00b-e65c6a27500d",
      "dishName": "Pizza",
      "quantity": 2,
      "unitPrice": 14.99,
      "linePrice": 29.98
    }
  ],
  "totalPrice": 29.98,
  "customerName": "Alice Johnson",
  "customerEmail": "alice.johnson@example.com",
  "deliveryAddress": {
    "street": "Gijselsstraat",
    "number": "31",
    "postalCode": "2140",
    "city": "Antwerp",
    "country": "Belgium"
  },
  "placedAt": "2025-10-21T14:35:00"
}