GET http://localhost:8080/api/customers/restaurants

###

GET http://localhost:8080/api/customers/restaurants/b52bd8cb-4f06-49df-948b-a5424ba0e964/dishes

###

POST http://localhost:8080/api/orders
Content-Type: application/json

{
  "restaurantId": "e0528938-1f04-4067-988c-c5daaf51b556",
  "lines": [
    {
      "dishId": "96144920-af2b-4663-8c8d-dadb8cba410a",
      "dishName": "Pizza",
      "quantity": 2,
      "unitPrice": 14.99,
      "linePrice": 29.98
    }
  ],
  "totalPrice": 29.98,
  "customerName": "Alice Johnson",
  "customerEmail": "alice.johnson@example.com",
  "deliveryAddress": {
    "street": "Gijselsstraat",
    "number": "31",
    "postalCode": "2140",
    "city": "Antwerp",
    "country": "Belgium"
  },
  "placedAt": "2025-10-21T14:35:00"
}