### Create restaurant (owner must be authenticated)
POST http://localhost:8080/api/restaurants
Content-Type: application/json

{
  "ownerId": "Michael",
  "name": "Trattoria Roma",
  "address": {
    "street": "Via Milano",
    "number": "12",
    "postalCode": "20100",
    "city": "Milan",
    "country": "Italy"
  },
  "emailAddress": "contact@trattoriaroma.it",
  "pictures": [
    "https://orders.co/static/99a59eec0735fca313bf2b93349bd5d6/5715c/Italian-Restaurant-Design-Creating-an-Inviting-Ambiance.webp"],
  "cuisineType": "ITALIAN",
  "minPrepTime": 15,
  "maxPrepTime": 25,
  "openingTime": "12:00",
  "closingTime": "23:00",
  "openDays": [
    "MONDAY",
    "FRIDAY",
    "SATURDAY",
    "SUNDAY"
  ]
}

###

POST http://localhost:8080/api/foodmenus/dishes
Content-Type: application/json

{
  "restaurantId": "a06da943-6787-4fab-86bc-fd2b3fd74f69",
  "name": "Pizza",
  "description": "yummy cheese and tomato sauce",
  "price": 14.99,
  "pictureUrl": "noPic",
  "tags": "italian,cheese,fast-food",
  "dishType": "MAIN"
}

###

PATCH http://localhost:8080/api/foodmenus/a06da943-6787-4fab-86bc-fd2b3fd74f69/dishes/7b99a95e-05e8-4a1d-95fc-866389cabf0d/publish

###

PATCH http://localhost:8080/api/foodmenus/b52bd8cb-4f06-49df-948b-a5424ba0e964/dishes/0824212d-adf0-4d11-981d-5b5938e1ae59
Content-Type: application/json

{
  "name": "Sushi",
  "description": "CHANGED",
  "price": 1000,
  "pictureUrl": "CHANGED",
  "tags": "CHANGED",
  "dishType": "DESSERT"
}
###

PATCH http://localhost:8080/api/foodmenus/b52bd8cb-4f06-49df-948b-a5424ba0e964/dishes/0824212d-adf0-4d11-981d-5b5938e1ae59/unpublish

###

PATCH http://localhost:8080/api/foodmenus/b52bd8cb-4f06-49df-948b-a5424ba0e964/dishes/61f7c6b0-ef03-43e3-9e46-b8c8dc15fc04/out-of-stock

###

PATCH http://localhost:8080/api/foodmenus/b52bd8cb-4f06-49df-948b-a5424ba0e964/dishes/61f7c6b0-ef03-43e3-9e46-b8c8dc15fc04/available

###

POST http://localhost:8080/api/foodmenus/dishes
Content-Type: application/json

{
  "restaurantId": "b52bd8cb-4f06-49df-948b-a5424ba0e964",
  "name": "Scrambled Eggs",
  "description": "delicious egg scramble",
  "price": 3.99,
  "pictureUrl": "noPic",
  "tags": "breakfast,cheese,fast-food",
  "dishType": "STARTER"
}

###

PATCH http://localhost:8080/api/foodmenus/b52bd8cb-4f06-49df-948b-a5424ba0e964/dishes/b15263ac-267c-449f-8ab9-7867a960c088
Content-Type: application/json

{
  "name": "2ND CHANGE",
  "description": "SECOND",
  "price": 1000,
  "pictureUrl": "SECOND",
  "tags": "SECOND",
  "dishType": "DESSERT"
}
###

###

POST http://localhost:8080/api/foodmenus/27a66c5f-2c7e-4e89-a453-14b07b7a4af9/dishes/apply-pending

###

PATCH http://localhost:8080/api/foodmenus/dishes/schedule
Content-Type: application/json

{
  "restaurantId": "b52bd8cb-4f06-49df-948b-a5424ba0e964",
  "dishIds": [
    "0824212d-adf0-4d11-981d-5b5938e1ae59",
    "4160b85b-f647-4013-8cc0-f6813d60619b"
  ],
  "publicationTime": "2025-10-14T22:02:00",
  "stateToBecome": "PUBLISHED"
}